Repository bouteillerAlan/archupdate, pull requests merged in 2023-11, with the labels that each got.

#12 Allow tray area and show by default
  a2n.archupdate.plasmoid/metadata.json
Labels: enhancement

#14 Add a count option for the aur
  README.md
  a2n.archupdate.plasmoid/contents/config/config.qml
  a2n.archupdate.plasmoid/contents/config/main.xml
  a2n.archupdate.plasmoid/contents/service/Updater.qml
  a2n.archupdate.plasmoid/contents/ui/Compact.qml
  a2n.archupdate.plasmoid/contents/ui/config/configInterval.qml
  git-assets/img/2022-11-19_14-35_1.png
  git-assets/img/2022-11-19_14-36.png
  git-assets/img/options-menu.png
  git-assets/img/screenshot.png
  git-assets/img/settings-win.png
  git-assets/img/sync.png
  git-assets/img/up.png
Labels: enhancement

#17 Show count in tooltip
  a2n.archupdate.plasmoid/contents/ui/Compact.qml
  a2n.archupdate.plasmoid/contents/ui/Tooltip.qml
Labels: enhancement

#13 QA branch for V4.1.1
  AUTHORS
  CHANGELOG
  README.md
  a2n.archupdate.plasmoid/contents/assets/arch-unknown.svg
  a2n.archupdate.plasmoid/contents/assets/software-update-available.svg
  a2n.archupdate.plasmoid/contents/config/config.qml
  a2n.archupdate.plasmoid/contents/config/main.xml
  a2n.archupdate.plasmoid/contents/service/Updater.qml
  a2n.archupdate.plasmoid/contents/ui/Compact.qml
  a2n.archupdate.plasmoid/contents/ui/Tooltip.qml
  a2n.archupdate.plasmoid/contents/ui/components/PlasmoidIcon.qml
  a2n.archupdate.plasmoid/contents/ui/config/configInterval.qml
  a2n.archupdate.plasmoid/metadata.json
  git-assets/img/2022-11-19_14-35_1.png
  git-assets/img/2022-11-19_14-36.png
  git-assets/img/options-menu.png
  git-assets/img/screenshot.png
  git-assets/img/settings-win.png
  git-assets/img/sync.png
  git-assets/img/up.png
  git-assets/img/v4.2.0/add-systray.png
  git-assets/img/v4.2.0/all-alt.png
  git-assets/img/v4.2.0/pling-shapes.png
  git-assets/img/v4.2.0/settings-panel-full.png
  git-assets/img/v4.2.0/tooltips.png
Labels: enhancement, QA needed

#21 deploy to the AUR
  .SRCINFO
  PKGBUILD
Labels: enhancement

#23 Added AUR installation method to README, minor cleanup
  README.md
Labels: documentation
