Repository bouteillerAlan/archupdate, pull requests merged in 2024-03, with the labels that each got.

#30 Fix tooltip
  a2n.archupdate.plasmoid/contents/ui/Compact.qml
  a2n.archupdate.plasmoid/contents/ui/Tooltip.qml
  a2n.archupdate.plasmoid/contents/ui/main.qml
Labels: QA needed, portage

#32 add aur repo
  README.md
Labels: documentation

#38 Update README.md
  README.md
Labels: documentation

#45 fix typo
  CHANGELOG
Labels: documentation

#53 Trying to improve the refresh trigger
  a2n.archupdate.plasmoid/contents/_toolbox/Cmd.qml
  a2n.archupdate.plasmoid/contents/_toolbox/Delay.qml
  a2n.archupdate.plasmoid/contents/config/config.qml
  a2n.archupdate.plasmoid/contents/config/main.xml
  a2n.archupdate.plasmoid/contents/service/Debug.qml
  a2n.archupdate.plasmoid/contents/service/Updater.qml
  a2n.archupdate.plasmoid/contents/ui/Compact.qml
  a2n.archupdate.plasmoid/contents/ui/Full.qml
  a2n.archupdate.plasmoid/contents/ui/archupdate.qml
  a2n.archupdate.plasmoid/contents/ui/components/ListItem.qml
  a2n.archupdate.plasmoid/contents/ui/config/showLog.qml
  a2n.archupdate.plasmoid/contents/ui/main.qml
Labels: enhancement, help wanted

#55 refresh on open full
  a2n.archupdate.plasmoid/contents/ui/Full.qml
Labels: enhancement

#56 add signal on tooltip
  a2n.archupdate.plasmoid/contents/ui/Tooltip.qml
Labels: bug

#58 Fix the concurrent cmd bug
  a2n.archupdate.plasmoid/contents/service/Updater.qml
  a2n.archupdate.plasmoid/contents/ui/main.qml
Labels: bug

#59 forget the version :c
  a2n.archupdate.plasmoid/metadata.json
Labels: enhancement

#60 forget the version :c
  a2n.archupdate.plasmoid/metadata.json
Labels: bug

#61 Fix typo: 'Install all update' -> 'Install all updates'
  a2n.archupdate.plasmoid/contents/ui/Full.qml
Labels: enhancement
